version: "3.8"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge